USGS-R/drb-estuary-salinity-ml

02_munge/src/munge_usgs.py
Processing column parameter codes to parameter names
Also includes pulling out time aggregation processing into a function and imports the yaml package
=> Process param codes to names

.gitignore, 03_it_analysis/src/it_analysis_data_prep.py
This PR is the initiation of the information theory analysis workflow. This PR only has the overall file organization and one function to try to keep it a size manageable for review. I plan to add functions to the `it_analysis_data_prep.py` that do preprocessing, verify time step, check for gaps etc.
=> begin to add information theory workflow

01_fetch/src/fetch_noaa_nerrs.py, 01_fetch/src/fetch_noaa_nos.py
**Things added/changed**
- Script added to fetch NOAA NERRS metadata and product data.
- Script downloads a csv for one product at a time.
- Script downloads a csv containing metadata for the product at the selected station.
- Did not integrate variables into configure.yaml as yet.
=> Add script to fetch NOAA NERRS data

.gitignore, 01_fetch/fetch_config.yaml, Snakefile
This is an initial set up for the Snakefile for the USGS NWIS fetch and munge steps. This only operates on the local files currently...I am having some trouble with the connector to S3.
To run it, activate your drb-estuary-salinity conda environment, navigate into the drb-estuary-salinity-ml directory, and type `snakemake --cores 1` in your Anaconda prompt.
NOAA data processing will be added to the Snakefile once @ted80810 has his config set up.
=> initial commit of snakefile for local workflow

03_it_analysis/src/it_analysis_data_prep.py
I added some functions for correlation analysis using the NWIS data and the current salt front location time series. I tried to make these as general as possible so that we can integrate new data sources as they become available. The functions that I've added are for selecting the sources (discharge, specific conductivity, met data etc) and sinks (salt front location) for analysis, lagging the source variables, and calculating the correlations across variables.
=> add functions for correlation analysis

02_munge/src/munge_usgs.py, data_exploration/data_exploration_config.yaml, data_exploration/src/gap_analysis.py, utils.py
Code to produce gap analysis plots for USGS NWIS data. This should be able to run on NOAA data produced by the munge step with just a few additions to the config.
=> add usgs gap analysis

03_it_analysis/src/it_analysis_data_prep.py, Snakefile
@galengorski  - I wanted to make sure the updated output file names look good to you before I make the pull request with the fully updated snakefile. These are the outputs I got from this update:
Feel free to merge if the look ok!
=> update output file naming

.gitignore, 01_fetch/src/fetch_noaa_nos.py, 02_munge/src/munge_noaa_nos.py
This is the first portion of the munge script that concatenates all the data by station_id and product into one csv.
=> Combine multiple CSVs Into one CSV S3

03_it_analysis/src/it_analysis_data_prep.py
I changed the file path in `it_analysis_data_prep.py` to call the updated salt front time series and changed the beginning of analysis to 2000. I am going to merge without review
=> change file path to include updated salt front time series

01_fetch/src/fetch_gridmet.R
This is adding an R script that pulls gridMET data using the climateR package in R. It isn't incorporated in the pipeline yet, but it could be if we decide this is the way we want to go. Right now the script has no config file. 
I manually made a dataframe with three stations and their lat/long. The stations are Ben Franklin Bridge (benfranklin), Lewes Delaware (lewes), and Reedy Island Jetty (reedyislandjetty). 
I also manually coded in the start date and end date for pulling data.
The for loop then loops through the three sites, pulling the nearest gridMET pixel to each location and then saving a daily csv for each site.
=> add fetch_gridmet.R

01_fetch/src/fetch_noaa_nos.py, 01_fetch/src/fetch_usgs.py, 02_munge/src/munge_noaa_nos.py, 02_munge/src/munge_usgs.py, Snakefile, utils.py
I updated the paths to use the aggregation levels (like 'H' or 'D') to store data files.
I made a folder called 'daily_summaries' to store the NOAA NOS daily summary data. That way we won't overwrite it if we every switched the config file to calculate daily NOAa NOS data (which would go in the 'D' folder.
Lastly, I added a helper to utils.py to convert a local filepath to an S3 filepath so we don't have to update so many lines of code when we change our directory  naming.
=> update folder structure with daily, hourly, etc.

01_fetch/src/fetch_coawst_model.py
@ted80810 - I can't get the load_COAWST_model_run() function to work...could you take a look and see what I might be missing?
I also don't know what the variables mean so I added space to add comments about what they do - could you look at the comments and maybe add some info about what the variables are?
=> add space to comment with notes about load_COAWST_model_run function

01_fetch/params_config_fetch_usgs_nwis.yaml
made small change to `params_config_fetch_usgs_nwis.yaml` start_dt option to test workflow
=> change params_config_fetch_usgs_nwis.yaml start_dt

01_fetch/params_config_fetch_usgs_nwis.yaml
changed `start_dt` to 2000-03-01 in `params_config_fetch_usgs_nwis.yaml`
=> made a small change to params_config_fetch_usgs_nwis.yaml chang start_dt

01_fetch/src/fetch_coawst_model.py
@ted80810 - what do you think about calculating the saltfront like this? It is getting all the values under 0.53, turning it into a dataframe, then getting the max salt value for each hour once it is already in a dataframe. That way there will only be one measurement per hour.
Really I would have liked to do the max piece in xarray, but I couldn't find enough documentation/examples to figure it out. This still takes about 5 mins for me to run, so while it's a little indirect, it gets the job done in the same amount of time.
=> Update sf calc

Snakefile_fetch_munge
This PR is for troubleshooting `Snakefile_fetch_munge`, it isn't ready to be merged, but I will add to it and add issues that reference this PR so hopefully we can get it working
=> troubleshooting fetch_munge snakefile

01_fetch/src/fetch_usgs_nwis.py, 02_munge/src/fill_discharge_prms.py, 02_munge/src/munge_noaa_nerrs.py, 02_munge/src/munge_usgs_nwis.py
Added creation of in/out data folders to pipeline scripts so someone running the pipeline from scratch won't have to create them manually.
=> add in/out folder creation

01_fetch/src/fetch_noaa_nerrs.py
add automatic fetch of s3 zipfile for nerrs data, if it doesn't exist locally
=> add s3 fetch of nerrs zipfile

01_fetch/params_config_fetch_coawst_model.yaml
Added urls to params file for 2016 COAWST data
=> add 2016 data links for coawst

03b_model/src/run_model.py, methods_exploration/it_functions.py
This is a small change to the `lag_data` function in `it_functions`. I have changed the lag so that if an input matrix is `[X,Y]` where `X` is the source and `Y` is the sink, the new `lag_data` function will produce a matrix `M_lagged` that is `[X-T, Y, Y-T]`, where `T` is the time lag. The previous version produced a matrix `[X-T, Y, Y-1]`. I have seen both lagging methods in the literature, you're either conditioning on the immediate history of `Y` or it's history at the time step of interest, but we want `Y-T` here. The other change that I made was to add a function called `find_bounds`, which finds the bounds of the time series of interest using percentiles. This is used for removing outliers for analysis.
=> Functional performance

03a_it_analysis/snakefile_func_perf.smk, 03b_model/model_config.yaml, 03b_model/src/run_model.py, Snakefile_b_ml_model_baseline
This involves no structural changes of code, which is why I am merging into main. It updates the hyperparameters and `run_id` and number of replicates in the `model_config.yaml` file and it comments out the data fetching steps from the snakefile so they are not rerun by default.
=> Update hyperparameters and run number comment out data pull in snakemake
